# filepath: /home/henrique-fraga/Ãrea de trabalho/projetos/octor-affiliates/netlify.toml
[build]
  publish = "./"
  command = "npm run lint:js . && npm run lint:css . && npm run lint:html . && npm run format ."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200